"""Subclass of Panel1, which is generated by wxFormBuilder."""

import wx
import wx01

# Implementing Panel1
class wx01Panel1( wx01.Panel1 ):
	def __init__( self, parent ):
		wx01.Panel1.__init__( self, parent )

	# Handlers for Panel1 events.
	def m_open_buttonOnButtonClick( self, event ):
		# TODO: Implement m_open_buttonOnButtonClick
		pass


