"""Subclass of Panel3, which is generated by wxFormBuilder."""

import wx
import wx01

# Implementing Panel3
class wx01Panel3( wx01.Panel3 ):
	def __init__( self, parent ):
		wx01.Panel3.__init__( self, parent )

	# Handlers for Panel3 events.
	def m_open_buttonOnButtonClick( self, event ):
		# TODO: Implement m_open_buttonOnButtonClick
		pass


