"""Subclass of Frame2, which is generated by wxFormBuilder."""

import wx
import wx01

# Implementing Frame2
class wx01Frame2( wx01.Frame2 ):
	def __init__( self, parent ):
		wx01.Frame2.__init__( self, parent )

